# -*- coding: utf-8 -*-
"""EDA PORTFOLIO PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uy3C-z_adhnUugWthhlTp0L7zOAZiVTO

# **                **Phase** 1: Import Libraries and Load Data**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv(r"/content/Property - Property.csv")

df

df.head(6)

df.tail(6)

df.tail(20)



pip install ydata-profiling

from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="My Report")
profile.to_file("yreport.html")

from google.colab import files
files.download("/content/yreport.html")

df.shape

print(df.shape)

df.columns

df.describe()

"""# **Phase 2: Data Cleaning and Preparation**"""

#Calculate and visualize the number of missing values in each column. Which columns have the most missing data?
missing_values=df.isnull().sum()
print(missing_values)

#Drop irrelevant columns (e.g., page_url or location_id if not used) to streamline the dataset.

df.drop('page_url', axis=1, inplace=True)

#• Imputation Strategy: Categorical/String columns: Fill Null/NA values with the string "Unknown".
categorical_cols = df.select_dtypes(include='object').columns
df[categorical_cols] = df[categorical_cols].fillna("Unknown")

df[categorical_cols].isnull().sum()

#Numerical columns: Fill Null/NA values with the mean of that column.
numeric_cols = df.select_dtypes(include='number').columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

#Verification: Check programmatically if all missing values have been successfully imputed.
df.isnull().sum().sum()

df.isnull().sum().sort_values(ascending=False)

"""## Data Transformation:**"""

#The area column contains mixed units (e.g., "10 Marla", "1 Kanal"). You must transform this into a single unit (i.e., marla).
import re
import numpy as np
import pandas as pd

def convert_area_to_marla(value):
    if pd.isna(value):
        return np.nan

    value = str(value).lower()

    # remove commas like 4,450 → 4450
    value = value.replace(",", "")

    # extract the numeric part
    match = re.search(r"\d+\.?\d*", value)
    if not match:
        return np.nan

    number = float(match.group())

    if "kanal" in value:
        return number * 20
    elif "marla" in value:
        return number
    else:
        return np.nan

df["area_in_marla"] = df["area"].apply(convert_area_to_marla)

df.head(20)

"""Phase 3: Outlier Detection

"""

# Phase 3: Outlier Detection
#• Numerical Outliers: Visualize and identify outliers in key numerical columns (especially price and the newly calculated area_in_marla).
#• Visual Check: Use Boxplots and Scatter plots to spot unrealistic values (e.g., a housecosting 0 PKR or an area of 0 Marla).

Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR
Q1,Q3,lower_limit,upper_limit

price_outliers = df[
    (df["price"] < lower_limit) |
    (df["price"] > upper_limit)
]

price_outliers.head()

price_outliers.shape[0]

df.describe()

Q1 = df["area_in_marla"].quantile(0.25)
Q3 = df["area_in_marla"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR
Q1,Q3,lower_limit,upper_limit

area_outliers = df[
    (df["area_in_marla"] < lower_limit) |
    (df["area_in_marla"] > upper_limit)
]

area_outliers.head(10)

df[df["area_in_marla"] > 17.8]

df[df["price"] > 36152500]

import matplotlib.pyplot as plt

plt.boxplot(df["price"].dropna())
plt.title("Price Outliers")
plt.show()

plt.boxplot(df["area_in_marla"].dropna())
plt.title("Area in Marla Outliers")
plt.show()

df = df[df["price"] > 0]
df

import seaborn as sns
import matplotlib.pyplot as plt

# Price boxplot
plt.figure(figsize=(10,5))
sns.boxplot(x=df["price"])
plt.title("Price Distribution & Outliers")
plt.show()

# Area boxplot
plt.figure(figsize=(10,5))
sns.boxplot(x=df["area_in_marla"])
plt.title("Area Distribution & Outliers")
plt.show()

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=df,
    x="area_in_marla",
    y="price"
    )

plt.title("Scatter Plot of Price vs Area (Outliers Highlighted)")
plt.xlabel("area_in_marla ")
plt.ylabel("Price")
plt.show()

"""Expolatory Data Analysis : Univariate analysis"""

#1. Price Distribution: Plot a histogram with KDE of the price column. Is it normally distributed or skewed?
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(9,7))

sns.histplot(
    df["price"],
    kde=True,
    bins=80
)

plt.title("Price Distribution with KDE")
plt.xlabel("Price (PKR)")
plt.ylabel("Frequency")
plt.show()

import numpy as np

sns.histplot(np.log(df["price"]), bins=50, kde=True)
plt.title("Log(Price) Distribution")
plt.show()

#Property Type Counts: Use a bar chart to show the count of listings for each property_type. Which type of property is most common on zameen.com?
property_type_counts = df["property_type"].value_counts()
print(property_type_counts)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

sns.countplot(
    data=df,
    x="property_type",
    order=df["property_type"].value_counts().index
)

plt.title("Property Type Counts on Zameen.com")
plt.xlabel("Property Type")
plt.ylabel("Number of Listings")
plt.xticks(rotation=45)
plt.show()

#City Representation: Which top 5 cities have the highest number of listings? Visualize this with a horizontal bar chart.
top_5_cities = df["city"].value_counts().head(5)
top_5_cities

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

sns.barplot(
    x=top_5_cities.values,
    y=top_5_cities.index
)

plt.title("Top 5 Cities with Highest Property Listings")
plt.xlabel("Number of Listings")
plt.ylabel("City")
plt.show()

#Area Distribution: Plot the distribution of area_in_marla. Are there any extreme values (e.g., thousands of Marlas) that might distort your analysis?


import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

sns.histplot(df["area_in_marla"], bins=50, kde=True)

plt.title("Distribution of Area (in Marla)")
plt.xlabel("Area (Marla)")
plt.ylabel("Frequency")
plt.show()

# Flag extreme area values
unrealistic_area = df[(df["area_in_marla"] <= 0) | (df["area_in_marla"] > 10000)]
print(unrealistic_area)

# Define thresholds
min_area = 1        # Anything below 1 Marla is unrealistic
max_area = 10000    # Anything above 10,000 Marla is extreme/outlier

# Flag unrealistic entries
unrealistic_area = df[(df['area_in_marla'] < min_area) | (df['area_in_marla'] > max_area)]
print(unrealistic_area[['property_id', 'area_in_marla', 'price', 'location', 'property_type']])

"""Phase 3: Outlier Detection
• Numerical Outliers: Visualize and identify outliers in key numerical columns (especially
price and the newly calculated area_in_marla).
• Visual Check: Use Boxplots and Scatter plots to spot unrealistic values (e.g., a house
costing 0 PKR or an area of 0 Marla).
"""

plt.figure(figsize=(10, 5))
sns.boxplot(x=df['price'])
plt.title("Boxplot of Property Prices")
plt.xlabel("Price (PKR)")
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(x=df['area_in_marla'])
plt.title("Boxplot of Property Area (in Marla)")
plt.xlabel("Area in Marla")
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='area_in_marla', y='price', data=df)
plt.title("Scatter Plot of Price vs Area")
plt.xlabel("Area (Marla)")
plt.ylabel("Price (PKR)")
plt.show()

# Remove rows with area > 10,000 Marla or price > 1e8 PKR (adjust thresholds as needed)
df_filtered = df[(df['area_in_marla'] < 10000) & (df['price'] < 1e8)]
print(df_filtered)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 5))
sns.boxplot(x=df['price'])
plt.title("Boxplot of Property Prices")
plt.xlabel("Price (PKR)")
plt.show()

plt.figure(figsize=(12, 5))
sns.boxplot(x=df['area_in_marla'])
plt.title("Boxplot of Property Area (in Marla)")
plt.xlabel("Area (Marla)")
plt.show()

plt.figure(figsize=(12, 6))
sns.scatterplot(x='area_in_marla', y='price', data=df)
plt.title("Scatter Plot of Price vs Area")
plt.xlabel("Area (Marla)")
plt.ylabel("Price (PKR)")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10,6))
sns.histplot(df['price'], kde=True, bins=50)
plt.title("Price Distribution")
plt.xlabel("Price (PKR)")
plt.ylabel("Count")
plt.show()

print("Skewness of price:", df['price'].skew())

plt.figure(figsize=(10,6))
sns.histplot(np.log1p(df['price']), kde=True, bins=50, color='orange')
plt.title("Log-transformed Price Distribution")
plt.xlabel("Log(Price + 1)")
plt.ylabel("Count")
plt.show()

"""B. Bivariate Analysis (Two Variables)
Explore the relationship between the target variable (price) and other features.

"""

#5. Price vs. Location (Boxplot): Create a boxplot comparing price across the top 3 cities
#(e.g., Lahore, Karachi, Islamabad). Which city has the highest median price and the most outliers?
import matplotlib.pyplot as plt

top_cities = ['Lahore', 'Karachi', 'Islamabad']
city_data = df[df['city'].isin(top_cities)]

plt.figure(figsize=(8, 5))
city_data.boxplot(column='price', by='city')
plt.title('Price Distribution Across Top 3 Cities')
plt.suptitle('')
plt.xlabel('City')
plt.ylabel('Price')
plt.show()

plt.figure(figsize=(8, 5))
plt.scatter(df['area_in_marla'], df['price'], alpha=0.5)
plt.xlabel('Area (Marla)')
plt.ylabel('Price')
plt.title('Price vs Area (Marla)')
plt.show()
#Does the price increase linearly with area?
#No, it does not show a clear linear relationship.
#Are there properties with small area but huge prices (potential errors or prime commercial spots)?
#Yes — very clearly.

#Bathrooms vs. Price: Do properties with more baths command a higher price? Visualize this relationship.
plt.figure(figsize=(8, 5))
df.boxplot(column='price', by='baths')
plt.title('Price Distribution by Number of Bathrooms')
plt.suptitle('')
plt.xlabel('Number of Bathrooms')
plt.ylabel('Price')
plt.show()
#Do properties with more bathrooms command higher prices?
#Yes — generally there is a positive relationship.

#Date vs. Count: Extract the year from date_added. How has the number of listings changed from year to year?
df=df.copy()
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['year'] = df['date_added'].dt.year

yearly_counts = df['year'].value_counts().sort_index()
print(yearly_counts)

plt.figure(figsize=(8,5))
plt.plot(yearly_counts.index, yearly_counts.values)
plt.xlabel('Year')
plt.ylabel('Number of Listings')
plt.title('Number of Property Listings per Year')
plt.show()

"""Multivariate Analysis (Three+ Variables)
Explore complex interactions.
9. Price vs. Area by City: Create a scatter plot of price vs. area_in_marla, but color the
points by city (hue).
o Do 10-Marla houses cost the same in Karachi as they do in Lahore?
"""

cities = ['Karachi', 'Lahore', 'Islamabad']
df_city = df[df['city'].isin(cities)].copy()

plt.figure(figsize=(8,5))

for city in cities:
    subset = df_city[df_city['city'] == city]
    plt.scatter(subset['area_in_marla'], subset['price'], alpha=0.5, label=city)

plt.xlabel('Area (Marla)')
plt.ylabel('Price')
plt.title('Price vs Area by City')
plt.legend()
plt.show()
#Do 10-Marla Houses Cost the Same in Karachi and Lahore?
# No, they do not cost the same.

df.head()

num_cols = ['price', 'area_in_marla', 'baths', 'bedrooms']
numerical_data = df[num_cols]

corr_matrix = numerical_data.corr()
print(corr_matrix)

plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix, annot=True, cmap='Blues', fmt=".2f")
plt.title("Correlation Matrix Heatmap")
plt.show()
#Which variable has the strongest positive correlation with price?
#The variable with the strongest positive correlation with price is bedrooms (0.30).

#11.Property Type Pricing: Create a bar chart showing the average price for each property_type, but split (grouped) by purpose (For Sale vs. For Rent).
import seaborn as sns
import matplotlib.pyplot as plt

# Group by property_type and purpose, then compute mean price
avg_price = df.groupby(['property_type', 'purpose'])['price'].mean().reset_index()
print(avg_price.head())

plt.figure(figsize=(10,6))
sns.barplot(data=avg_price, x='property_type', y='price', hue='purpose')
plt.title('Average Price by Property Type and Purpose')
plt.ylabel('Average Price')
plt.xlabel('Property Type')
plt.xticks(rotation=45)
plt.show()

"""Phase 5: Business Questions (Q&A)
You must answer the following 10 questions using data visualization and statistical
summaries:
"""

#Which city shows the highest growth in high-value properties (properties above a certain price threshold) over the years?
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

# Extract year
df['year'] = df['date_added'].dt.year

# Define high-value threshold (90th percentile)
threshold = df['price'].quantile(0.90)
high_value_df = df[df['price'] > threshold]
city_year_counts = (
    high_value_df
    .groupby(['city', 'year'])
    .size()
    .reset_index(name='high_value_count')
)

city_year_counts.head()
growth_df = (
    city_year_counts
    .sort_values(['city', 'year'])
    .groupby('city')['high_value_count']
    .agg(['first', 'last'])
)

growth_df['growth'] = growth_df['last'] - growth_df['first']

growth_df = growth_df.sort_values('growth', ascending=False)

growth_df.head()
highest_growth_city = growth_df.index[0]
highest_growth_value = growth_df.iloc[0]['growth']

highest_growth_city, highest_growth_value

#What are the most popular property types in each city, and how has this preference changed over time?
city_type_year = (
    df.groupby(['city', 'year', 'property_type'])
      .size()
      .reset_index(name='count')
)

city_type_year.head()
city_type_total = (
    df.groupby(['city', 'property_type'])
      .size()
      .reset_index(name='count')
)

# Get most popular type per city
most_popular_overall = (
    city_type_total
    .sort_values(['city', 'count'], ascending=[True, False])
    .groupby('city')
    .first()
    .reset_index()
)

most_popular_overall.head()
yearly_leader = (
    city_type_year
    .sort_values(['city', 'year', 'count'], ascending=[True, True, False])
    .groupby(['city', 'year'])
    .first()
    .reset_index()
)

yearly_leader.head()
# Pivot for easier comparison
pivot_table = city_type_year.pivot_table(
    index=['city', 'year'],
    columns='property_type',
    values='count',
    fill_value=0
)

pivot_table.head()

df_clean = df[['price', 'bedrooms', 'city', 'property_type']].dropna()
df_clean = df_clean[df_clean['bedrooms'] < 15]

city_bedroom_price = (
    df_clean.groupby(['city', 'bedrooms'])['price']
    .mean()
    .reset_index()
)

city_bedroom_price.head()

#3. How do property prices vary with the number of bedrooms across different cities and property types?
df_clean = df[['price', 'bedrooms', 'city', 'property_type']].dropna()
bedroom_price = (
    df_clean.groupby('bedrooms')['price']
    .agg(['mean', 'median', 'count'])
    .reset_index()
)

bedroom_price
bedroom_price = (
    df_clean.groupby('bedrooms')['price']
    .agg(['mean', 'median', 'count'])
    .reset_index()
)

bedroom_price
city_pivot = city_bedroom_price.pivot(
    index='bedrooms',
    columns='city',
    values='price'
)

city_pivot
type_bedroom_price = (
    df_clean.groupby(['property_type', 'bedrooms'])['price']
    .mean()
    .reset_index()
)

type_pivot = type_bedroom_price.pivot(
    index='bedrooms',
    columns='property_type',
    values='price'
)

type_pivot
full_analysis = (
    df_clean.groupby(['city', 'property_type', 'bedrooms'])['price']
    .mean()
    .reset_index()
)

full_analysis.head()

#Which agencies have the most listings in high-demand areas (specific locations or cities)?
top_cities = df['city'].value_counts().head(5).index
high_demand_df = df[df['city'].isin(top_cities)]
agency_counts = (
    high_demand_df['agency']
    .value_counts()
    .reset_index()
)

agency_counts.columns = ['agency', 'listing_count']

agency_counts.head(10)

#Is there a seasonal trend in property listings (e.g., are more houses listed in specific montz
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['year'] = df['date_added'].dt.year
df['month'] = df['date_added'].dt.month
df['month_name'] = df['date_added'].dt.month_name()
monthly_counts = (
    df.groupby('month')
      .size()
      .reset_index(name='listing_count')
      .sort_values('month')
)

monthly_counts

#Which agents are most active in high-value property markets?
threshold = df['price'].quantile(0.90)
high_value_df = df[df['price'] > threshold]
agent_counts = (
    high_value_df['agent']
    .value_counts()
    .reset_index()
)

agent_counts.columns = ['agent', 'high_value_listings']

agent_counts.head(10)



pip install ydata-profiling

from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="My Report")
profile.to_file("yreport.html")

from google.colab import files
files.download("/content/yreport.html")